name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-28"

# compatibility_flags = [ "nodejs_compat" ]

 [vars]
DATABASE_URL = "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOWU0NTk5OTgtMWIyMS00ZDEwLTkzZGUtOGRmMmUyNzUyNGUyIiwidGVuYW50X2lkIjoiMjhjZGMyNDE3YmJjMDVhY2NmYmU4NTAxYzgyOTc3ZDRjMzg4ODgzMjg2ZWY0OWNiMzUwZjc4NjBhMmYwODRhNCIsImludGVybmFsX3NlY3JldCI6ImE3NTA1YzcyLTI5OGQtNDk1My1hZjBiLWY2OGU5MDAwYTI5OSJ9.T6PhMFxYLEqGp4EQUjh0LzrvCZJL0fVPVNNEUW52ygw"
JWT_SECRET = "aadsasds"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1